# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=128)),
                ('lastName', models.CharField(max_length=128)),
                ('twitter', models.CharField(max_length=128, unique=True)),
                ('email_1', models.EmailField(blank=True, max_length=128, null=True, unique=True)),
                ('email_2', models.EmailField(blank=True, max_length=128, null=True, unique=True)),
                ('link_1', models.URLField(blank=True, null=True)),
                ('link_2', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showName', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='show',
            field=models.ForeignKey(default=101010, on_delete=django.db.models.deletion.CASCADE, to='webGenApp.Show'),
        ),
    ]
