# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webGenApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='firstName',
            new_name='xirstName',
        ),
    ]
