# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webGenApp', '0002_auto_20170604_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='xirstName',
            new_name='firstName',
        ),
    ]
