# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webGenApp', '0005_auto_20170607_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picChoice',
            field=models.CharField(choices=[('images/base1.jpg', 'pic1'), ('images/base2.jpg', 'pic2'), ('images/base3.jpg', 'pic3')], default='images/base2.jpg', max_length=25),
        ),
    ]
