# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webGenApp', '0006_auto_20170607_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profilePics'),
        ),
    ]
