# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webGenApp', '0007_person_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='twitter',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
